### ISSUE TITLE
ArachisPheno: Customization

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ArachisPheno#3]
The ArachisPheno doesn't have to be an exact replicate of the Arabidopsis portal.  We will need only certain features, at least, in the beginning.  This issue is to help us gradually settle on which features, UI included, we need.  The features list should evolve as we work through the site and the data we have keeping in mind the flexibility factor for future needs.

**Comment by svengato** [comment]
I am happy to make a first attempt at customization (for your review).
1. Are there any restrictions on image sources? (I will look for public peanut images, PeanutBase seems to only have small ones)
2. Whom should we list as collaborators? (NCGR, Iowa State, etc) I will also credit the original AraPheno project.

**Comment by sdash-github** [comment]
A few thoughts about this.

#### Header
-- The PB (PeanutBase) image at the top left is sort of the representative image we have been using in presentations and posters.
(https://peanutbase.org/sites/all/themes/peanutbase_theme/images/peanutbase_logo.png)
-- Along with this the header color scheme and the PeanutBase text will make it look like part of PeanutBase (guiding theme here is: As much as possible it should not look like foreign to PB).

#### Iframe
-- We have successfully used, at PB and LIS, Iframing independent sites into a PB page to give it a very native look while preserving the top level UI-Navigation elements.
-- Examples are:
(https://peanutbase.org/gbrowse_aradu1.0),  
(https://peanutbase.org/germplasm/gigwa),  etc. 

If we decide to use it within an Iframe, probably it should be when the data is public.  So the CSS parts for mainly the header part  may be kept minimal and  flexible for later consideration.

**Comment by sdash-github** [comment]
#### About the credit:
Let me think about a bit more, as it is being developed, initially, with funding from a project and if we need to acknowledge this fact explicitly.
But you can go ahead with what seems suitable to you for now and we revisit the issue later.

**Comment by svengato** [comment]
3. Who should be the e-mail contact person?
4. Copyright dates? (2020?)

**Comment by sdash-github** [comment]
3.  In the final version I think it should be (https://peanutbase.org/contact) which is a list of individual emails.
  But for now during development I don't want to flood everybody's inbox unnecessarily.  You can keep your or my email, sdash@ncgr.org,  depending on how often it is triggered when you are working on the site.
4. Today's date is fine with me.

**Comment by adf-ncgr** [comment]
from Sven: 
> Customization is partially accomplished. None of it is checked in yet, but it should be visible on the development site. The plan is to do it in three waves: (a) AraPheno -> ArachisPheno and other species changes, (b) institutional changes, (c) spelling and grammar corrections.

regarding the image question from earlier, maybe the current weedy backdrop could simply be replaced with a solid color and the small image Sudhansu suggested from the main site be put somewhere without trying to make it fill space.

We'll need to gut/replace the news/twitter items. my personal preference would be to just go minimalist, by commenting out blocks where we think we might put something someday, and just focus on core functionality as much as possible. 
I'd suggest we disable the RNA-seq slider as well as whatever the thingy is that wants to use flash.

**Comment by svengato** [comment]
Do we want to keep any of the links on the Links page? Some are Arabidopsis-centric.

Besides PeanutBase, are there any we should add? (for example, the Community links on PeanutBase)

**Comment by svengato** [comment]
I do not see an easy way to guarantee that the (small) peanut part of the background image will be visible. See what you think of the one I have up now. Some actual peanuts appear as you scroll down.

**Comment by adf-ncgr** [comment]
very peanut-ty, but a bit hard to read the text. I'll defer to Sudhansu on questions of style, though.

**Comment by sdash-github** [comment]
I am working on a quick and simple mockup of the front page for Sven with the idea that it can be iframed in PB when necessary.

**Comment by svengato** [comment]
I made a simpler version combining your suggestions, see what you think of it.

**Comment by sdash-github** [comment]
Here is a GoogleDrive slide that should give you an idea of a simple interface.
https://docs.google.com/presentation/d/11KW-OFo0IYQQ2a--P1bH7LXmViNp-tOoWfFGf1HIZC4/edit#slide=id.g828d4cbe32_0_80  

- I have conceived it to fit into the PB theme and future iframe-ing. We may want to keep it as flexible blocks that we can shuffle if necessary.  
- The blocks I have shown are only suggestive and may change. I haven't thought about it yet.
(I am preparing data and will have a better idea of the block elements and other UI elements as we start looking at the data)
- I am thinking of removing the word 'public' from the front page block titles as that may imply we have private data too. We don't know that yet-- but that will be great if we can have both public and priv datasets.
- Let us evolve the look and feel as we go.

**Comment by svengato** [comment]
I will leave the background like this for now, and move on to replacing the AraPheno institutions and links.

**Comment by sdash-github** [comment]
But do you plan to revisit and change the look later?

**Comment by svengato** [comment]
Yes, we can evolve it as we go.

**Comment by svengato** [comment]
I started customizing the institutional links, and removed AraPheno news items. Is there a peanut Twitter feed?

**Comment by sdash-github** [comment]
Yes, pl see (https://peanutbase.org) footer (https://twitter.com/peanutbaseorg)

**Comment by svengato** [comment]
I replaced (or commented out) institutional links over the weekend, and corrected the most obvious spelling and grammar mistakes this morning. Still to do:
1. "How to Cite ArachisPheno" FAQ
2. Remaining references to arapheno.1001genomes.org
3. Remaining "arapheno" references (module and settings) in the python code
4. Process for adding and curating studies and phenotypes
5. How to generate download.zip
6. Remove commented-out institutional links
7. Configure DOI and e-mail servers
8. Follow up on getting the Docker version to work (this version is uncontainerized)
9. Remove other undesired features (Flash, RNASeq?)
10. Confirm that we do not need the "Impressum" in the footer (is that a European legal requirement?)
11-99. Anything else you notice.

**Comment by svengato** [comment]
Do we have a DataCite account (or "prefix")?
https://search.datacite.org
This is for linking studies to citations.

**Comment by svengato** [comment]
For now, I replaced all uses (as opposed to mentions) of "arapheno.1001genomes.org" in our HTML files with "<BASE_URL>". <BASE_URL> should eventually be our production site.

**Comment by sdash-github** [comment]
As far as I am aware we haven't used datacite  yet for either LIS or 
PB.  We have been using a pubmed id straight.

**Comment by svengato** [comment]
Okay, I will look into replacing it with PubMed.

**Comment by svengato** [comment]
Please let me know if we need more (or less) institutional links before the presentation (see the About and Links pages).

**Comment by sdash-github** [comment]
-- My affiliation is NCGR, not ISU.
-- "ArachisPheno is a XXcentralXX repository for population scale 
phenotype data for//Arachis//(peanut) species."

Can you give me admin level access to change some of these type of 
contents or just lead me to the html/template file that I can edit when 
I get in the mood.
Thanks.

**Comment by sdash-github** [comment]
The mail to field should be set to peanutbase-contact@iastate.edu 
<peanutbase-contact@iastate.edu> instead of just me or Andrew.  These 
are the sort of things I can change later.

**Comment by svengato** [comment]
> -- "ArachisPheno is a XXcentralXX repository for population scale 
> phenotype data for//Arachis//(peanut) species."

XX = remove?

> Can you give me admin level access to change some of these type of 
> contents or just lead me to the html/template file that I can edit when 
> I get in the mood.

html/home/about.html
html/home/links.html

**Comment by sdash-github** [comment]
Yes, remove. I couldn't immediately find any markup for strikethrough.

**Comment by svengato** [comment]
Feel free to make those institutional changes (depending on mood).

**Comment by svengato** [comment]
e-mail is now configured correctly, at least for this development version. For example, ArachisPheno automatically sends the user a status message when they submit a study or it gets curated or published.

**Comment by svengato** [comment]
The Download Database feature (from the Home page) now works (except for some issues with the PLINK output, which should be fixable). As in the original AraPheno, it only downloads a preexisting database archive, it does not generate one on the fly. To generate such a snapshot, run
`python manage.py generate_database_dump`
from the command line (from the ArachisPheno/arapheno directory).

However, this earlier issue

> Here is a GoogleDrive slide that should give you an idea of a simple interface.
> https://docs.google.com/presentation/d/11KW-OFo0IYQQ2a--P1bH7LXmViNp-tOoWfFGf1HIZC4/edit#slide=id.g828d4cbe32_0_80

omits the Download Database, Take a Tour, and Feedback & Issues features. Let me know if you really want to remove those.

**Comment by sdash-github** [comment]
1. The idea is not to remove, but to gradually introduce them as we go 
and feel the necessity.
2. Therefore, hiding those interfaces is the ideal solution for now. And 
please document how/where you hid them so that I can revisit them later.
3. For the Wednesday meeting, please do not display anything that gives 
the impression 'Download' or 'Downoad in bulk'. She is very averse to 
that phrase.
4. Feedback should be a link to 'https://peanutbase.org/contact'. 
ArachisPheno is not being developed to become an independent site, 
rather as one of the parts of PeanutBase.
5. The homepage block with search box and large letters describing what 
ArachisPheno is should be reduced to just the searchbox. Then, it will 
nicely fit into the Peanutbase iframe.

**Comment by svengato** [comment]
Tentative changes - let me know if they satisfy the above requests.
- Commented out the Home page introductory text, leaving only the global search box. (5)
- Also changed the example global search terms.
- Commented out Download Database and Take a Tour features. (2,3)
- Feedback & Issues now links to the PeanutBase contact page. (4)

**Comment by sdash-github** [comment]
Looks like we can get the data via REST API without having to login-- 
haven't tested thoroughly though? Can something be done about that, at 
least tentatively?

**Comment by svengato** [comment]
> Looks like we can get the data via REST API without having to login--

Confirmed - I will prioritize fixing that.

**Comment by svengato** [comment]
The REST API should be secure now - try it while logged out.

**Comment by sdash-github** [comment]
> The REST API should be secure now - try it while logged out.
>
Yeah, can't get to it incognito; works.

**Comment by svengato** [comment]
> 1. The idea is not to remove, but to gradually introduce them as we go
and feel the necessity.
> 2. Therefore, hiding those interfaces is the ideal solution for now. And
please document how/where you hid them so that I can revisit them later.

To restore the Data Download and Take a Tour features, undo the relevant HTML comment tags from this commit (lines 69 & 74, 87 & 95, and 106-107): https://github.com/legumeinfo/ArachisPheno/commit/f5503faaf66fa7b5274d5f33617879f63a17b6ef

**Comment by svengato** [comment]
Shall we close this one and split off individual issues?

**Comment by sdash-github** [comment]
Yes, if you want.  We can always start a new issue for other customization.
