### ISSUE TITLE
Authentication to access ArachisPheno site

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ArachisPheno#6]
On April-08-2020, a week from today, there is a meeting with the researchers whose data we are using here.  They have insisted to keep the data private until it is published (in future).  But we need to share with them this utility. Can we  have some kind of authenticated access ready for them before the meeting?
Refer:  #2  
From the schema it looks like there is author, group and public access for studies.  This could work for us too for this purpose.  Or go the quick temporary way Andrew suggested in #2, "... use apache basic authentication (after we get it running via apache, that is)"

**Comment by svengato** [comment]
Does each participant in the presentation need their own username, or will a single test account suffice?

**Comment by sdash-github** [comment]
> Does each participant in the presentation need their own username,
No, we don't plan to do that. A single guest account, no admin 
privilege, whose pw we can change would suffice for now. Thanks for asking.

**Comment by svengato** [comment]
Basic user authentication now works, I will send the username & password separately. Let me know if you encounter any problems.

To do (if desired/possible):
1. For the login/logout pages, remove the Data-Tools-About-Links-FAQ-Logout options at upper right.
2. Allow redirection to a page other than the home page.

**Comment by sdash-github** [comment]
> Basic user authentication now works, I will send the username & 
> password separately. Let me know if you encounter any problems.
I can get in and get out without a problem. Thanks. Things are falling 
into place.
