### ISSUE TITLE
The Flash-y Explorer: disable or give guidance?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/ArachisPheno#8]
My curiosity finally got the better of me enough to figure out the rather byzantine rigamarole required to enable flash to work in chrome on a specific site. The result (for AraPheno) is shown below, showing perhaps that stomata in Spanish Arabidopsis tend to be larger than those in Scandinavian countries (due to the falling of the rains mainly on the plains? or maybe another climate-related factor)
![image](https://user-images.githubusercontent.com/2009605/78519379-60b1b680-7780-11ea-85ba-cbe1c390e734.png)

It also works on ArachisPheno, though I have yet to find a cute example. Seems like a reasonably flexible tool for display along various dimensions, could probably be reimplemented in something less universally deprecated than Flash but would take some time. Just wanted to note that it's actually possible to use this, if you are willing to be sufficiently sycophantic to your browser. I followed steps given here:
https://www.freecodecamp.org/news/how-to-enable-adobe-flash-player-in-google-chrome/
which worked as long as I followed them to the very end rather than assuming that it would work after the basic setting to Allow Flash was enabled

**Comment by svengato** [comment]
Does this mean we should leave the Explorer feature in place?

**Comment by adf-ncgr** [comment]
my inclination is to leave it in place.

**Comment by svengato** [comment]
Removed in commit 264a415.
