### ISSUE TITLE
OperationalError at phenotype and study

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ArachisPheno#9]
Going to any phenotype or the study page shows:
OperationalError at /phenotype/19/
no such column: phenotypedb_submission.is_private
...   ...   ...
Error during template rendering
In template /home/svengato/ArachisPheno/html/base.html, error at line 0
no such column: phenotypedb_submission.is_private

...   ...   ...

**Comment by svengato** [comment]
I was experimenting with making submissions private (issue #2). The application should work now (though private data are not yet implemented).

**Comment by svengato** [comment]
Closing, refer to issue #2.
